
path: /home/anton/bitrix24/mysql_debug.sql # путь к файлу
shrink_log: 2MB # Обезать лог при достижении. -1 или удалить для отключения

server:
  enable: true # Не запускать ws сервер
  port: 8081

console_filter: # Фильтр что падает в кончоль
  module: crm
  trace: false
  pause: true     # отключить вывовд в консоль